import { createHash, randomUUID } from 'node:crypto';
import { constants } from 'node:fs';
import type { Stats } from 'node:fs';
import {
  open,
  lstat,
  mkdir,
  readdir,
  realpath,
  rename,
  rmdir,
  statfs,
  unlink,
} from 'node:fs/promises';
import type { FileHandle } from 'node:fs/promises';
import { dirname, isAbsolute, join, parse, relative, resolve, sep } from 'node:path';

import { parseManagedRelativePath } from '@mystery-operations/shared/storage';

import {
  BACKUP_MAX_DIRECTORIES,
  BACKUP_MAX_FILE_BYTES,
  BACKUP_MAX_FILES,
  BACKUP_MAX_MANIFEST_BYTES,
  BACKUP_MAX_TOTAL_BYTES,
  ControlledBackupError,
  backupWindowsPathKey,
  manifestSha256,
  parseBackupCompleteMarkerV1,
  parseBackupManifestV1,
  parseBackupPayloadPath,
  serializeBackupCompleteMarkerV1,
  serializeBackupManifestV1,
  type BackupFileCategory,
  type BackupManifestFileV1,
  type BackupManifestV1,
} from './backup-contracts.js';
import type { ProjectDataRoot } from './project-data-root.js';

const DATABASE_PAYLOAD_PATH = parseBackupPayloadPath('payload/database/rednote.sqlite', 'DATABASE');
const OWNER_FILE = '.rednote-backup-owner.json';
const COPY_BUFFER_BYTES = 64 * 1024;
const SPACE_MARGIN_BYTES = 1024 * 1024;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/iu;

export interface BackupDatabaseIdentity {
  readonly migrationFingerprint: string;
  readonly schemaVersion: number;
}

export interface BackupManagedFileReference {
  readonly category: Exclude<BackupFileCategory, 'DATABASE'>;
  readonly expectedSha256: string | null;
  readonly expectedSizeBytes: number | null;
  readonly managedPath: string;
}

export interface ControlledBackupDatabaseVerifier {
  readonly enumerateManagedFiles: (
    snapshotPath: string,
    signal?: AbortSignal,
  ) => readonly BackupManagedFileReference[];
  readonly inspectSnapshot: (snapshotPath: string) => BackupDatabaseIdentity;
}

export interface ControlledBackupDatabaseAdapter extends ControlledBackupDatabaseVerifier {
  readonly createSnapshot: (
    destinationPath: string,
    signal?: AbortSignal,
  ) => Promise<BackupDatabaseIdentity>;
  readonly estimateSnapshotBytes: () => number;
}

/** @internal Test-only durability seam; it is deliberately not exported by the package barrel. */
export interface ControlledBackupDurabilityPort {
  readonly syncDirectory?: (path: string) => Promise<void>;
  readonly syncFile?: (path: string) => Promise<void>;
}

export interface CreateControlledBackupOptions {
  readonly appVersion: string;
  readonly buildCommit: string;
  readonly database: ControlledBackupDatabaseAdapter;
  readonly databasePath: string;
  readonly root: ProjectDataRoot;
  /** Existing writable directory selected by the user; the backup name is generated by this core. */
  readonly selectedBackupRoot: string;
  readonly availableBytes?: () => number;
  readonly signal?: AbortSignal;
  readonly v2DataVersion: number;
  readonly now?: () => Date;
  readonly randomId?: () => string;
  /** @internal deterministic durability evidence only. */
  readonly internalDurabilityPort?: ControlledBackupDurabilityPort;
}

export interface VerifyControlledBackupOptions {
  readonly backupPath: string;
  readonly database: ControlledBackupDatabaseVerifier;
  readonly signal?: AbortSignal;
}

export interface ControlledBackupVerification {
  readonly manifest: BackupManifestV1;
  readonly manifestSha256: string;
}

export interface ControlledBackupResult {
  readonly backupName: string;
  readonly durability:
    'SYNC_REQUESTS_COMPLETED' | 'DIRECTORY_SYNC_UNAVAILABLE' | 'PUBLISHED_DURABILITY_UNKNOWN';
  readonly manifestSha256: string;
  readonly operationId: string;
  readonly totals: BackupManifestV1['totals'];
}

interface NodeIdentity {
  readonly dev: number;
  readonly ino: number;
}
interface FileIdentity extends NodeIdentity {
  readonly mtimeMs: number;
  readonly size: number;
}
interface OwnedEntry {
  readonly identity: NodeIdentity;
  readonly kind: 'directory' | 'file';
}
interface SourceFile {
  readonly category: BackupFileCategory;
  readonly expectedSha256: string | null;
  readonly expectedSizeBytes: number | null;
  readonly identity: FileIdentity;
  readonly payloadPath: string;
  readonly sourcePath: string;
}
interface StagingState {
  directories: number;
  readonly operationId: string;
  readonly owned: Map<string, OwnedEntry>;
  readonly path: string;
}

function fail(code: ConstructorParameters<typeof ControlledBackupError>[0]): ControlledBackupError {
  return new ControlledBackupError(code);
}
function stable(error: unknown, fallback: Parameters<typeof fail>[0]): ControlledBackupError {
  return error instanceof ControlledBackupError ? error : fail(fallback);
}
function databaseFailure(error: unknown): ControlledBackupError {
  if (error instanceof ControlledBackupError) return error;
  const code =
    typeof error === 'object' && error !== null && 'code' in error
      ? (error as { readonly code: unknown }).code
      : undefined;
  if (code === 'ABORTED' || code === 'MAINTENANCE_REQUIRED' || code === 'LIMIT_EXCEEDED')
    return fail(code);
  return fail('DATABASE_FAILED');
}
function snapshotFailure(error: unknown): ControlledBackupError {
  if (error instanceof ControlledBackupError) return error;
  const code =
    typeof error === 'object' && error !== null && 'code' in error
      ? (error as { readonly code: unknown }).code
      : undefined;
  if (code === 'ABORTED' || code === 'MAINTENANCE_REQUIRED' || code === 'LIMIT_EXCEEDED')
    return fail(code);
  return fail('SNAPSHOT_FAILED');
}
function checkAborted(signal: AbortSignal | undefined): void {
  if (signal?.aborted === true) throw fail('ABORTED');
}
async function yieldToEventLoop(signal: AbortSignal | undefined): Promise<void> {
  await new Promise<void>((resolve) => setImmediate(resolve));
  checkAborted(signal);
}
function nodeIdentity(status: Stats): NodeIdentity {
  return { dev: status.dev, ino: status.ino };
}
function fileIdentity(status: Stats): FileIdentity {
  return { ...nodeIdentity(status), mtimeMs: status.mtimeMs, size: status.size };
}
function sameNode(left: NodeIdentity, right: NodeIdentity): boolean {
  return left.dev === right.dev && left.ino === right.ino;
}
function sameFile(left: FileIdentity, right: FileIdentity): boolean {
  return sameNode(left, right) && left.mtimeMs === right.mtimeMs && left.size === right.size;
}
function isWithin(parent: string, candidate: string): boolean {
  const difference = relative(parent, candidate);
  return (
    difference === '' ||
    (!difference.startsWith(`..${sep}`) && difference !== '..' && !isAbsolute(difference))
  );
}

async function checkedNode(path: string, expected: 'directory' | 'file'): Promise<Stats> {
  let status: Stats;
  try {
    status = await lstat(path);
  } catch {
    throw fail('INVALID_PATH');
  }
  if (status.isSymbolicLink()) throw fail('PATH_LINK_NOT_ALLOWED');
  if (expected === 'directory' ? !status.isDirectory() : !status.isFile())
    throw fail('INVALID_PATH');
  if (expected === 'file' && status.nlink !== 1) throw fail('PATH_LINK_NOT_ALLOWED');
  return status;
}
async function checkedDirectoryTree(path: string): Promise<string> {
  const resolved = resolve(path);
  const root = parse(resolved).root;
  let current = root;
  await checkedNode(current, 'directory');
  for (const segment of relative(root, resolved).split(sep).filter(Boolean)) {
    current = join(current, segment);
    await checkedNode(current, 'directory');
  }
  let canonical: string;
  try {
    canonical = await realpath(resolved);
  } catch {
    throw fail('INVALID_PATH');
  }
  if (!isWithin(resolved, canonical) || !isWithin(canonical, resolved))
    throw fail('PATH_LINK_NOT_ALLOWED');
  return resolved;
}
function addExact(left: number, right: number): number {
  const total = left + right;
  if (!Number.isSafeInteger(total) || total > BACKUP_MAX_TOTAL_BYTES) throw fail('LIMIT_EXCEEDED');
  return total;
}
async function assertCapacity(
  directory: string,
  required: number,
  availableBytes: (() => number) | undefined,
): Promise<void> {
  if (!Number.isSafeInteger(required) || required < 0 || required > BACKUP_MAX_TOTAL_BYTES)
    throw fail('LIMIT_EXCEEDED');
  let available: number;
  try {
    const stats = await statfs(directory);
    const observed = Number(BigInt(stats.bavail) * BigInt(stats.bsize));
    available = availableBytes === undefined ? observed : Math.min(observed, availableBytes());
  } catch {
    throw fail('INSUFFICIENT_SPACE');
  }
  if (!Number.isSafeInteger(available) || available < required) throw fail('INSUFFICIENT_SPACE');
}
function operationOwner(operationId: string): string {
  return JSON.stringify({ format: 'rednote-controlled-backup-owner', operationId, version: 1 });
}
function backupName(now: Date, operationId: string): string {
  const timestamp = now.toISOString();
  if (!UUID.test(operationId) || timestamp !== new Date(timestamp).toISOString())
    throw fail('INVALID_PATH');
  return `rednote-backup-${timestamp.replace(/[-:.]/gu, '')}-${operationId.toLowerCase()}`;
}

async function writeExclusive(
  path: string,
  content: string,
  onCreated?: () => Promise<void>,
): Promise<FileIdentity> {
  let handle: FileHandle | undefined;
  try {
    handle = await open(path, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY, 0o600);
    await onCreated?.();
    const bytes = Buffer.from(content, 'utf8');
    let offset = 0;
    while (offset < bytes.length) {
      const result = await handle.write(bytes, offset, bytes.length - offset, offset);
      if (result.bytesWritten < 1) throw fail('COPY_FAILED');
      offset += result.bytesWritten;
    }
    await handle.sync();
    return fileIdentity(await handle.stat());
  } catch (error) {
    throw stable(error, 'PUBLISH_FAILED');
  } finally {
    await handle?.close().catch(() => undefined);
  }
}
async function createStaging(
  selectedBackupRoot: string,
  randomId: () => string,
): Promise<StagingState> {
  for (let attempt = 0; attempt < 4; attempt += 1) {
    const operationId = randomId();
    if (!UUID.test(operationId)) throw fail('INVALID_PATH');
    const path = join(selectedBackupRoot, `.${operationId.toLowerCase()}.rednote-backup-staging`);
    try {
      await mkdir(path, { mode: 0o700 });
    } catch {
      continue;
    }
    const owned = new Map<string, OwnedEntry>();
    owned.set('', {
      identity: nodeIdentity(await checkedNode(path, 'directory')),
      kind: 'directory',
    });
    const state: StagingState = {
      directories: 1,
      operationId: operationId.toLowerCase(),
      owned,
      path,
    };
    try {
      await writeExclusive(join(path, OWNER_FILE), operationOwner(state.operationId), () =>
        recordFile(state, OWNER_FILE, join(path, OWNER_FILE)),
      );
      return state;
    } catch (error) {
      await cleanupStaging(state).catch(() => undefined);
      throw stable(error, 'PUBLISH_FAILED');
    }
  }
  throw fail('ALREADY_EXISTS');
}
async function mkdirOwned(state: StagingState, relativePath: string): Promise<string> {
  if (state.owned.has(relativePath)) return join(state.path, ...relativePath.split('/'));
  state.directories += 1;
  if (state.directories > BACKUP_MAX_DIRECTORIES) throw fail('LIMIT_EXCEEDED');
  const path = join(state.path, ...relativePath.split('/'));
  try {
    await mkdir(path, { mode: 0o700 });
    state.owned.set(relativePath, {
      identity: nodeIdentity(await checkedNode(path, 'directory')),
      kind: 'directory',
    });
    return path;
  } catch (error) {
    throw stable(error, 'PUBLISH_FAILED');
  }
}
async function recordFile(state: StagingState, relativePath: string, path: string): Promise<void> {
  state.owned.set(relativePath, {
    identity: nodeIdentity(await checkedNode(path, 'file')),
    kind: 'file',
  });
}
async function sourceFileIdentity(path: string): Promise<FileIdentity> {
  return fileIdentity(await checkedNode(path, 'file'));
}

async function buildSources(
  root: ProjectDataRoot,
  inventory: readonly BackupManagedFileReference[],
): Promise<SourceFile[]> {
  const keys = new Set<string>();
  const sources: SourceFile[] = [];
  for (const item of inventory) {
    let managedPath: ReturnType<typeof parseManagedRelativePath>;
    try {
      managedPath = parseManagedRelativePath(item.managedPath, item.category);
    } catch {
      throw fail('INTEGRITY_FAILED');
    }
    const payloadPath = parseBackupPayloadPath(`payload/${managedPath}`, item.category);
    const key = backupWindowsPathKey(payloadPath);
    if (keys.has(key)) throw fail('PATH_CONFLICT');
    keys.add(key);
    const sourcePath = root.resolve(managedPath);
    if (!isWithin(root.rootPath, sourcePath)) throw fail('INVALID_PATH');
    await checkedDirectoryTree(dirname(sourcePath));
    sources.push({
      category: item.category,
      expectedSha256: item.expectedSha256,
      expectedSizeBytes: item.expectedSizeBytes,
      identity: await sourceFileIdentity(sourcePath),
      payloadPath,
      sourcePath,
    });
  }
  if (sources.length > BACKUP_MAX_FILES - 1) throw fail('LIMIT_EXCEEDED');
  return sources.sort((left, right) => left.payloadPath.localeCompare(right.payloadPath, 'en'));
}

async function copyBounded(
  source: SourceFile,
  target: string,
  signal: AbortSignal | undefined,
  onCreated: () => Promise<void>,
): Promise<BackupManifestFileV1> {
  checkAborted(signal);
  const before = await sourceFileIdentity(source.sourcePath);
  if (!sameFile(before, source.identity)) throw fail('FILE_CHANGED');
  if (before.size > BACKUP_MAX_FILE_BYTES) throw fail('LIMIT_EXCEEDED');
  if (source.expectedSizeBytes !== null && before.size !== source.expectedSizeBytes)
    throw fail('FILE_CHANGED');
  let input: FileHandle | undefined;
  let output: FileHandle | undefined;
  let size = 0;
  const digest = createHash('sha256');
  try {
    input = await open(source.sourcePath, constants.O_RDONLY);
    if (!sameFile(before, fileIdentity(await input.stat()))) throw fail('FILE_CHANGED');
    output = await open(target, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY, 0o600);
    await onCreated();
    const buffer = Buffer.allocUnsafe(COPY_BUFFER_BYTES);
    while (true) {
      checkAborted(signal);
      const read = await input.read(buffer, 0, buffer.length, null);
      if (read.bytesRead === 0) break;
      digest.update(buffer.subarray(0, read.bytesRead));
      let offset = 0;
      while (offset < read.bytesRead) {
        checkAborted(signal);
        const written = await output.write(buffer, offset, read.bytesRead - offset, null);
        if (written.bytesWritten < 1) throw fail('COPY_FAILED');
        offset += written.bytesWritten;
      }
      size = addExact(size, read.bytesRead);
      if (size > BACKUP_MAX_FILE_BYTES) throw fail('LIMIT_EXCEEDED');
      await yieldToEventLoop(signal);
    }
    await output.sync();
  } catch (error) {
    throw stable(error, 'COPY_FAILED');
  } finally {
    await output?.close().catch(() => undefined);
    await input?.close().catch(() => undefined);
  }
  const after = await sourceFileIdentity(source.sourcePath);
  const targetIdentity = await sourceFileIdentity(target);
  if (!sameFile(before, after) || targetIdentity.size !== size) throw fail('FILE_CHANGED');
  const hash = digest.digest('hex');
  if (source.expectedSha256 !== null && source.expectedSha256 !== hash)
    throw fail('INTEGRITY_FAILED');
  return {
    category: source.category,
    relativePath: parseBackupPayloadPath(source.payloadPath),
    sha256: hash,
    sizeBytes: size,
  };
}
async function hashFile(
  path: string,
  expected: FileIdentity | undefined,
  signal: AbortSignal | undefined,
): Promise<{ hash: string; size: number }> {
  const before = await sourceFileIdentity(path);
  if (expected !== undefined && !sameFile(before, expected)) throw fail('FILE_CHANGED');
  if (before.size > BACKUP_MAX_FILE_BYTES) throw fail('LIMIT_EXCEEDED');
  let input: FileHandle | undefined;
  const digest = createHash('sha256');
  let total = 0;
  try {
    input = await open(path, constants.O_RDONLY);
    if (!sameFile(before, fileIdentity(await input.stat()))) throw fail('FILE_CHANGED');
    const buffer = Buffer.allocUnsafe(COPY_BUFFER_BYTES);
    while (true) {
      checkAborted(signal);
      const result = await input.read(buffer, 0, buffer.length, null);
      if (result.bytesRead === 0) break;
      digest.update(buffer.subarray(0, result.bytesRead));
      total = addExact(total, result.bytesRead);
      if (total > BACKUP_MAX_FILE_BYTES) throw fail('LIMIT_EXCEEDED');
      await yieldToEventLoop(signal);
    }
  } catch (error) {
    throw stable(error, 'INTEGRITY_FAILED');
  } finally {
    await input?.close().catch(() => undefined);
  }
  const after = await sourceFileIdentity(path);
  if (!sameFile(before, after) || total !== before.size) throw fail('FILE_CHANGED');
  return { hash: digest.digest('hex'), size: total };
}
async function readBounded(
  path: string,
  maximum: number,
  signal: AbortSignal | undefined,
): Promise<Uint8Array> {
  const before = await sourceFileIdentity(path);
  if (before.size > maximum) throw fail('LIMIT_EXCEEDED');
  let input: FileHandle | undefined;
  try {
    input = await open(path, constants.O_RDONLY);
    if (!sameFile(before, fileIdentity(await input.stat()))) throw fail('FILE_CHANGED');
    const output = Buffer.allocUnsafe(before.size + 1);
    let offset = 0;
    while (offset < output.length) {
      checkAborted(signal);
      const result = await input.read(output, offset, output.length - offset, offset);
      if (result.bytesRead === 0) break;
      offset += result.bytesRead;
      await yieldToEventLoop(signal);
    }
    if (offset > maximum) throw fail('LIMIT_EXCEEDED');
    if (!sameFile(before, fileIdentity(await input.stat())) || offset !== before.size)
      throw fail('FILE_CHANGED');
    return output.subarray(0, offset);
  } catch (error) {
    throw stable(error, 'INVALID_MANIFEST');
  } finally {
    await input?.close().catch(() => undefined);
  }
}

async function scanOwned(state: StagingState): Promise<Map<string, OwnedEntry>> {
  const found = new Map<string, OwnedEntry>();
  const stack: Array<{ depth: number; path: string; relativePath: string }> = [
    { depth: 0, path: state.path, relativePath: '' },
  ];
  let directories = 0;
  let files = 0;
  while (stack.length > 0) {
    const current = stack.pop();
    if (current === undefined || current.depth > 64) throw fail('STAGING_OWNERSHIP_INVALID');
    const status = await lstat(current.path).catch(() => {
      throw fail('STAGING_OWNERSHIP_INVALID');
    });
    if (status.isSymbolicLink()) throw fail('STAGING_OWNERSHIP_INVALID');
    if (status.isDirectory()) {
      if (++directories > BACKUP_MAX_DIRECTORIES) throw fail('STAGING_OWNERSHIP_INVALID');
      found.set(current.relativePath, { identity: nodeIdentity(status), kind: 'directory' });
      const entries = await readdir(current.path, { withFileTypes: true }).catch(() => {
        throw fail('STAGING_OWNERSHIP_INVALID');
      });
      for (const entry of entries)
        stack.push({
          depth: current.depth + 1,
          path: join(current.path, entry.name),
          relativePath:
            current.relativePath === '' ? entry.name : `${current.relativePath}/${entry.name}`,
        });
    } else if (status.isFile() && status.nlink === 1) {
      if (++files > BACKUP_MAX_FILES + 3) throw fail('STAGING_OWNERSHIP_INVALID');
      found.set(current.relativePath, { identity: nodeIdentity(status), kind: 'file' });
    } else throw fail('STAGING_OWNERSHIP_INVALID');
    await yieldToEventLoop(undefined);
  }
  return found;
}
async function cleanupStaging(state: StagingState): Promise<void> {
  const owner = await readBounded(join(state.path, OWNER_FILE), 1024, undefined).catch(() => {
    throw fail('STAGING_OWNERSHIP_INVALID');
  });
  if (Buffer.from(owner).toString('utf8') !== operationOwner(state.operationId))
    throw fail('STAGING_OWNERSHIP_INVALID');
  const found = await scanOwned(state);
  if (found.size !== state.owned.size) throw fail('STAGING_OWNERSHIP_INVALID');
  for (const [relativePath, expected] of state.owned) {
    const actual = found.get(relativePath);
    if (
      actual === undefined ||
      actual.kind !== expected.kind ||
      !sameNode(actual.identity, expected.identity)
    )
      throw fail('STAGING_OWNERSHIP_INVALID');
  }
  const entries = [...state.owned.entries()].sort(
    ([left], [right]) =>
      right.split('/').length - left.split('/').length || right.localeCompare(left),
  );
  for (const [relativePath, expected] of entries) {
    const target = relativePath === '' ? state.path : join(state.path, ...relativePath.split('/'));
    const status = await lstat(target).catch(() => {
      throw fail('STAGING_OWNERSHIP_INVALID');
    });
    const kind = status.isDirectory()
      ? 'directory'
      : status.isFile() && status.nlink === 1
        ? 'file'
        : undefined;
    if (kind !== expected.kind || !sameNode(nodeIdentity(status), expected.identity))
      throw fail('STAGING_OWNERSHIP_INVALID');
    try {
      if (kind === 'directory') await rmdir(target);
      else await unlink(target);
    } catch {
      throw fail('STAGING_OWNERSHIP_INVALID');
    }
  }
}

function expectedInventory(
  manifest: BackupManifestV1,
  inventory: readonly BackupManagedFileReference[],
): void {
  const expected = new Map<string, BackupManagedFileReference>();
  for (const item of inventory) {
    let managed: ReturnType<typeof parseManagedRelativePath>;
    try {
      managed = parseManagedRelativePath(item.managedPath, item.category);
    } catch {
      throw fail('INTEGRITY_FAILED');
    }
    const payload = parseBackupPayloadPath(`payload/${managed}`, item.category);
    const key = backupWindowsPathKey(payload);
    if (expected.has(key)) throw fail('INTEGRITY_FAILED');
    expected.set(key, item);
  }
  const managedFiles = manifest.files.filter((file) => file.category !== 'DATABASE');
  if (managedFiles.length !== expected.size) throw fail('INTEGRITY_FAILED');
  for (const file of managedFiles) {
    const item = expected.get(backupWindowsPathKey(file.relativePath));
    if (item === undefined || item.category !== file.category) throw fail('INTEGRITY_FAILED');
    if (item.expectedSha256 !== null && item.expectedSha256 !== file.sha256)
      throw fail('INTEGRITY_FAILED');
    if (item.expectedSizeBytes !== null && item.expectedSizeBytes !== file.sizeBytes)
      throw fail('INTEGRITY_FAILED');
  }
}

async function verifyDirectory(
  backupPath: string,
  database: ControlledBackupDatabaseVerifier,
  signal: AbortSignal | undefined,
  ownerOperationId?: string,
): Promise<ControlledBackupVerification> {
  checkAborted(signal);
  const directory = await checkedDirectoryTree(backupPath);
  const allowed = new Set(['manifest.json', 'COMPLETE.json', 'payload']);
  if (ownerOperationId !== undefined) {
    allowed.add(OWNER_FILE);
    const owner = await readBounded(join(directory, OWNER_FILE), 1024, signal).catch(() => {
      throw fail('STAGING_OWNERSHIP_INVALID');
    });
    if (Buffer.from(owner).toString('utf8') !== operationOwner(ownerOperationId))
      throw fail('STAGING_OWNERSHIP_INVALID');
  }
  const top = await readdir(directory, { withFileTypes: true }).catch(() => {
    throw fail('INVALID_MANIFEST');
  });
  if (top.length !== allowed.size || top.some((entry) => !allowed.has(entry.name)))
    throw fail('INVALID_MANIFEST');
  const manifestBytes = await readBounded(
    join(directory, 'manifest.json'),
    BACKUP_MAX_MANIFEST_BYTES,
    signal,
  );
  let manifest: BackupManifestV1;
  let manifestHash: string;
  try {
    manifest = parseBackupManifestV1(manifestBytes);
    manifestHash = manifestSha256(Buffer.from(manifestBytes).toString('utf8'));
    const complete = parseBackupCompleteMarkerV1(
      await readBounded(join(directory, 'COMPLETE.json'), 1024, signal),
    );
    if (complete.manifestSha256 !== manifestHash) throw fail('INTEGRITY_FAILED');
  } catch (error) {
    throw stable(error, 'INVALID_MANIFEST');
  }
  const databasePath = join(directory, ...DATABASE_PAYLOAD_PATH.split('/'));
  try {
    const identity = database.inspectSnapshot(databasePath);
    if (
      identity.schemaVersion !== manifest.source.schemaVersion ||
      identity.migrationFingerprint !== manifest.source.migrationFingerprint
    )
      throw fail('INTEGRITY_FAILED');
    expectedInventory(manifest, database.enumerateManagedFiles(databasePath, signal));
  } catch (error) {
    throw error instanceof ControlledBackupError ? error : fail('INTEGRITY_FAILED');
  }
  const expected = new Map(manifest.files.map((file) => [file.relativePath, file]));
  const found = new Set<ReturnType<typeof parseBackupPayloadPath>>();
  const payloadDirectory = join(directory, 'payload');
  await checkedNode(payloadDirectory, 'directory');
  const stack: Array<{ depth: number; path: string; prefix: string }> = [
    { depth: 1, path: payloadDirectory, prefix: 'payload' },
  ];
  let directories = 1;
  let files = 0;
  while (stack.length > 0) {
    const current = stack.pop();
    if (current === undefined || current.depth > 64) throw fail('LIMIT_EXCEEDED');
    const entries = await readdir(current.path, { withFileTypes: true }).catch(() => {
      throw fail('INTEGRITY_FAILED');
    });
    for (const entry of entries) {
      checkAborted(signal);
      const child = join(current.path, entry.name);
      const payloadPath = `${current.prefix}/${entry.name}`;
      const status = await lstat(child).catch(() => {
        throw fail('INTEGRITY_FAILED');
      });
      if (status.isSymbolicLink()) throw fail('PATH_LINK_NOT_ALLOWED');
      if (status.isDirectory()) {
        if (++directories > BACKUP_MAX_DIRECTORIES) throw fail('LIMIT_EXCEEDED');
        stack.push({ depth: current.depth + 1, path: child, prefix: payloadPath });
      } else if (status.isFile() && status.nlink === 1) {
        if (++files > BACKUP_MAX_FILES) throw fail('LIMIT_EXCEEDED');
        let parsed: ReturnType<typeof parseBackupPayloadPath>;
        try {
          parsed = parseBackupPayloadPath(payloadPath);
        } catch {
          throw fail('INTEGRITY_FAILED');
        }
        const item = expected.get(parsed);
        if (item === undefined || status.size !== item.sizeBytes) throw fail('INTEGRITY_FAILED');
        const hashed = await hashFile(child, fileIdentity(status), signal);
        if (hashed.hash !== item.sha256 || hashed.size !== item.sizeBytes)
          throw fail('INTEGRITY_FAILED');
        found.add(parsed);
      } else throw fail('PATH_LINK_NOT_ALLOWED');
      await yieldToEventLoop(signal);
    }
  }
  if (found.size !== expected.size || [...found].some((item) => !expected.has(item)))
    throw fail('INTEGRITY_FAILED');
  return Object.freeze({ manifest, manifestSha256: manifestHash });
}

async function syncRegularFile(
  path: string,
  port: ControlledBackupDurabilityPort | undefined,
): Promise<void> {
  if (port?.syncFile !== undefined) return port.syncFile(path);
  const handle = await open(path, constants.O_RDONLY);
  try {
    await handle.sync();
  } finally {
    await handle.close();
  }
}
async function syncDirectory(
  path: string,
  port: ControlledBackupDurabilityPort | undefined,
): Promise<void> {
  if (port?.syncDirectory !== undefined) return port.syncDirectory(path);
  const handle = await open(path, constants.O_RDONLY);
  try {
    await handle.sync();
  } finally {
    await handle.close();
  }
}
async function syncForPublish(
  staging: StagingState,
  port: ControlledBackupDurabilityPort | undefined,
): Promise<boolean> {
  for (const [relativePath, entry] of staging.owned)
    if (entry.kind === 'file')
      await syncRegularFile(join(staging.path, ...relativePath.split('/')), port);
  let unavailable = false;
  for (const [relativePath, entry] of [...staging.owned.entries()].sort(
    ([left], [right]) => right.split('/').length - left.split('/').length,
  )) {
    if (entry.kind !== 'directory') continue;
    try {
      await syncDirectory(
        relativePath === '' ? staging.path : join(staging.path, ...relativePath.split('/')),
        port,
      );
    } catch {
      unavailable = true;
    }
  }
  return unavailable;
}
async function assertSelectedRoot(
  root: ProjectDataRoot,
  selectedBackupRoot: string,
): Promise<string> {
  if (!isAbsolute(selectedBackupRoot) || selectedBackupRoot.includes('\0'))
    throw fail('INVALID_PATH');
  const selected = await checkedDirectoryTree(selectedBackupRoot);
  const source = await checkedDirectoryTree(root.rootPath);
  if (selected === source || isWithin(source, selected) || isWithin(selected, source))
    throw fail('PATH_CONFLICT');
  return selected;
}

export async function createControlledBackupSnapshot(
  options: CreateControlledBackupOptions,
): Promise<ControlledBackupResult> {
  const now = options.now ?? (() => new Date());
  const randomId = options.randomId ?? randomUUID;
  checkAborted(options.signal);
  const selectedRoot = await assertSelectedRoot(options.root, options.selectedBackupRoot);
  const operationId = randomId().toLowerCase();
  const createdAt = now().toISOString();
  const name = backupName(new Date(createdAt), operationId);
  const destination = join(selectedRoot, name);
  if (
    await lstat(destination)
      .then(() => true)
      .catch(() => false)
  )
    throw fail('ALREADY_EXISTS');
  const expectedDatabasePath = resolve(options.root.databaseDirectory, 'rednote.sqlite');
  if (resolve(options.databasePath) !== expectedDatabasePath) throw fail('PATH_CONFLICT');
  const databaseSourceIdentity = await sourceFileIdentity(expectedDatabasePath);
  let estimate: number;
  try {
    estimate = options.database.estimateSnapshotBytes();
  } catch (error) {
    throw databaseFailure(error);
  }
  if (!Number.isSafeInteger(estimate) || estimate < 0) throw fail('DATABASE_FAILED');
  await assertCapacity(
    selectedRoot,
    addExact(estimate, SPACE_MARGIN_BYTES),
    options.availableBytes,
  );
  let staging: StagingState | undefined;
  let published = false;
  try {
    staging = await createStaging(selectedRoot, () => operationId);
    const payload = await mkdirOwned(staging, 'payload');
    await mkdirOwned(staging, 'payload/database');
    const databaseTarget = join(payload, 'database', 'rednote.sqlite');
    let databaseIdentity: BackupDatabaseIdentity;
    try {
      databaseIdentity = await options.database.createSnapshot(databaseTarget, options.signal);
      await recordFile(staging, DATABASE_PAYLOAD_PATH, databaseTarget);
      const inspected = options.database.inspectSnapshot(databaseTarget);
      if (
        inspected.schemaVersion !== databaseIdentity.schemaVersion ||
        inspected.migrationFingerprint !== databaseIdentity.migrationFingerprint
      )
        throw fail('INTEGRITY_FAILED');
    } catch (error) {
      throw snapshotFailure(error);
    }
    if (!sameFile(databaseSourceIdentity, await sourceFileIdentity(expectedDatabasePath)))
      throw fail('FILE_CHANGED');
    let inventory: readonly BackupManagedFileReference[];
    try {
      inventory = options.database.enumerateManagedFiles(databaseTarget, options.signal);
    } catch (error) {
      throw databaseFailure(error);
    }
    const sources = await buildSources(options.root, inventory);
    let actualTotal = (await sourceFileIdentity(databaseTarget)).size;
    for (const source of sources) actualTotal = addExact(actualTotal, source.identity.size);
    await assertCapacity(
      selectedRoot,
      addExact(actualTotal, SPACE_MARGIN_BYTES),
      options.availableBytes,
    );
    const databaseHash = await hashFile(databaseTarget, undefined, options.signal);
    const files: BackupManifestFileV1[] = [
      {
        category: 'DATABASE',
        relativePath: DATABASE_PAYLOAD_PATH,
        sha256: databaseHash.hash,
        sizeBytes: databaseHash.size,
      },
    ];
    for (const source of sources) {
      let directory = '';
      for (const part of dirname(source.payloadPath).split('/')) {
        directory = directory === '' ? part : `${directory}/${part}`;
        await mkdirOwned(staging, directory);
      }
      const target = join(staging.path, ...source.payloadPath.split('/'));
      const copied = await copyBounded(source, target, options.signal, () =>
        recordFile(staging as StagingState, source.payloadPath, target),
      );
      files.push(copied);
    }
    files.sort((left, right) => left.relativePath.localeCompare(right.relativePath, 'en'));
    const manifest = {
      format: 'rednote-controlled-directory-backup',
      backupFormatVersion: 1,
      status: 'COMPLETE',
      createdAt,
      timeZone: 'UTC',
      source: {
        workspaceId: options.root.marker.instanceId,
        appVersion: options.appVersion,
        buildCommit: options.buildCommit,
        dataRootFormat: 'rednote-project-data',
        dataRootVersion: options.root.marker.version,
        v2DataVersion: options.v2DataVersion,
        schemaVersion: databaseIdentity.schemaVersion,
        migrationFingerprint: databaseIdentity.migrationFingerprint,
      },
      compatibilityPolicyVersion: 1,
      files,
      totals: {
        fileCount: files.length,
        sizeBytes: files.reduce((total, file) => addExact(total, file.sizeBytes), 0),
      },
    } as const satisfies BackupManifestV1;
    const serialized = serializeBackupManifestV1(manifest);
    const manifestPath = join(staging.path, 'manifest.json');
    const completePath = join(staging.path, 'COMPLETE.json');
    await writeExclusive(manifestPath, serialized, () =>
      recordFile(staging as StagingState, 'manifest.json', manifestPath),
    );
    await writeExclusive(
      completePath,
      serializeBackupCompleteMarkerV1(manifestSha256(serialized)),
      () => recordFile(staging as StagingState, 'COMPLETE.json', completePath),
    );
    await verifyDirectory(staging.path, options.database, options.signal, staging.operationId);
    checkAborted(options.signal);
    const unavailableBefore = await syncForPublish(staging, options.internalDurabilityPort);
    const ownerEntry = staging.owned.get(OWNER_FILE);
    const ownerPath = join(staging.path, OWNER_FILE);
    if (
      ownerEntry === undefined ||
      !sameNode(nodeIdentity(await checkedNode(ownerPath, 'file')), ownerEntry.identity)
    )
      throw fail('STAGING_OWNERSHIP_INVALID');
    await unlink(ownerPath);
    staging.owned.delete(OWNER_FILE);
    if (
      await lstat(destination)
        .then(() => true)
        .catch(() => false)
    )
      throw fail('ALREADY_EXISTS');
    await rename(staging.path, destination);
    published = true;
    try {
      await verifyDirectory(destination, options.database, options.signal);
      let unavailable = unavailableBefore;
      for (const [relativePath, entry] of staging.owned) {
        const target =
          relativePath === '' ? destination : join(destination, ...relativePath.split('/'));
        if (entry.kind === 'file') await syncRegularFile(target, options.internalDurabilityPort);
        else {
          try {
            await syncDirectory(target, options.internalDurabilityPort);
          } catch {
            unavailable = true;
          }
        }
      }
      try {
        await syncDirectory(selectedRoot, options.internalDurabilityPort);
      } catch {
        unavailable = true;
      }
      return Object.freeze({
        backupName: name,
        durability: unavailable ? 'DIRECTORY_SYNC_UNAVAILABLE' : 'SYNC_REQUESTS_COMPLETED',
        manifestSha256: manifestSha256(serialized),
        operationId,
        totals: manifest.totals,
      });
    } catch {
      return Object.freeze({
        backupName: name,
        durability: 'PUBLISHED_DURABILITY_UNKNOWN',
        manifestSha256: manifestSha256(serialized),
        operationId,
        totals: manifest.totals,
      });
    }
  } catch (error) {
    if (!published && staging !== undefined) {
      try {
        await cleanupStaging(staging);
      } catch {
        throw fail('STAGING_OWNERSHIP_INVALID');
      }
    }
    throw stable(error, 'PUBLISH_FAILED');
  }
}

export async function verifyControlledBackupSnapshot(
  options: VerifyControlledBackupOptions,
): Promise<ControlledBackupVerification> {
  try {
    return await verifyDirectory(resolve(options.backupPath), options.database, options.signal);
  } catch (error) {
    throw stable(error, 'INTEGRITY_FAILED');
  }
}
